// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry          = require("bs-platform/lib/js/curry.js");
var Didact         = require("./didact/didact.bs.js");
var TodoMvc        = require("./todoMvc.bs.js");
var DidactDom      = require("./didact/didactDom.bs.js");
var Pervasives     = require("bs-platform/lib/js/pervasives.js");
var DidactElements = require("./didact/didactElements.bs.js");

function createElement(_, _$1) {
  return Didact.component(/* record */[
              /* debugName */"App",
              /* render */(function (param) {
                  var send = param[/* send */2];
                  return DidactElements.div(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* :: */[
                              DidactElements.button(/* Some */[(function () {
                                        return Curry._1(send, /* Increment */0);
                                      })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* :: */[
                                    Didact.stringToElement("Increment"),
                                    /* [] */0
                                  ], /* () */0),
                              /* :: */[
                                DidactElements.h3(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* :: */[
                                      Didact.stringToElement(Pervasives.string_of_int(param[/* state */0])),
                                      /* [] */0
                                    ], /* () */0),
                                /* :: */[
                                  DidactElements.button(/* Some */[(function () {
                                            return Curry._1(send, /* Decrement */1);
                                          })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* :: */[
                                        Didact.stringToElement("Decrement"),
                                        /* [] */0
                                      ], /* () */0),
                                  /* [] */0
                                ]
                              ]
                            ], /* () */0);
                }),
              /* initialState */(function () {
                  return 0;
                }),
              /* reducer */(function (action, state) {
                  if (action !== 0) {
                    return /* Update */[state - 1 | 0];
                  } else {
                    return /* Update */[state + 1 | 0];
                  }
                })
            ]);
}

var App = /* module */[/* createElement */createElement];

var match = document.getElementById("container");

if (match !== null) {
  var instance = DidactDom.render(TodoMvc.createElement(/* [] */0, /* () */0), match);
  DidactDom.hotUpdate(TodoMvc.createElement(/* [] */0, /* () */0), match, instance);
} else {
  console.log("No dom element found :(");
}

exports.App = App;
/* match Not a pure module */
