// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List           = require("bs-platform/lib/js/list.js");
var Block          = require("bs-platform/lib/js/block.js");
var Curry          = require("bs-platform/lib/js/curry.js");
var Didact         = require("./didact/didact.bs.js");
var DidactElements = require("./didact/didactElements.bs.js");

function createElement(_, _$1) {
  return Didact.component(/* record */[
              /* debugName */"TodoMVC",
              /* render */(function (self) {
                  return DidactElements.div(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* :: */[
                              DidactElements.header(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["header"], /* None */0, /* :: */[
                                    DidactElements.h1(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* :: */[
                                          Didact.stringToElement("todos"),
                                          /* [] */0
                                        ], /* () */0),
                                    /* :: */[
                                      DidactElements.input(/* None */0, /* Some */[(function (e) {
                                                var value = e.target.value;
                                                return Curry._1(self[/* send */2], /* InputNewTodo */Block.__(1, [value]));
                                              })], /* Some */[(function (prim) {
                                                console.log(prim);
                                                return /* () */0;
                                              })], /* None */0, /* Some */[self[/* state */0][/* newTodo */1]], /* Some */["new-todo"], /* Some */["What needs to be done?"], /* [] */0, /* () */0),
                                      /* [] */0
                                    ]
                                  ], /* () */0),
                              /* :: */[
                                DidactElements.h1(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* :: */[
                                      Didact.stringToElement(self[/* state */0][/* newTodo */1]),
                                      /* [] */0
                                    ], /* () */0),
                                /* :: */[
                                  DidactElements.button(/* Some */[(function () {
                                            return Curry._1(self[/* send */2], /* AddTodo */Block.__(0, [/* record */[
                                                            /* id */"blue",
                                                            /* title */"new todo added",
                                                            /* completed : false */0
                                                          ]]));
                                          })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* :: */[
                                        Didact.stringToElement("Add todo"),
                                        /* [] */0
                                      ], /* () */0),
                                  /* :: */[
                                    DidactElements.section(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["main"], /* None */0, /* :: */[
                                          DidactElements.input(/* None */0, /* Some */[(function (prim) {
                                                    console.log(prim);
                                                    return /* () */0;
                                                  })], /* None */0, /* None */0, /* None */0, /* Some */["toggle-all"], /* None */0, /* [] */0, /* () */0),
                                          /* :: */[
                                            DidactElements.ul(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["todo-list"], /* None */0, /* :: */[
                                                  Didact.listToElement(List.map((function (todo) {
                                                              return DidactElements.div(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* :: */[
                                                                          DidactElements.span(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* :: */[
                                                                                Didact.stringToElement(todo[/* title */1]),
                                                                                /* [] */0
                                                                              ], /* () */0),
                                                                          /* [] */0
                                                                        ], /* () */0);
                                                            }), self[/* state */0][/* todos */0])),
                                                  /* [] */0
                                                ], /* () */0),
                                            /* [] */0
                                          ]
                                        ], /* () */0),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ], /* () */0);
                }),
              /* initialState */(function () {
                  return /* record */[
                          /* todos : :: */[
                            /* record */[
                              /* id */"1",
                              /* title */"Make it work",
                              /* completed : true */1
                            ],
                            /* :: */[
                              /* record */[
                                /* id */"2",
                                /* title */"Make it correct",
                                /* completed : false */0
                              ],
                              /* :: */[
                                /* record */[
                                  /* id */"3",
                                  /* title */"Make it fast",
                                  /* completed : false */0
                                ],
                                /* [] */0
                              ]
                            ]
                          ],
                          /* newTodo */"",
                          /* editing */"",
                          /* nowShowing : All */0
                        ];
                }),
              /* reducer */(function (action, state) {
                  if (action.tag) {
                    return /* Update */[/* record */[
                              /* todos */state[/* todos */0],
                              /* newTodo */action[0],
                              /* editing */state[/* editing */2],
                              /* nowShowing */state[/* nowShowing */3]
                            ]];
                  } else {
                    return /* Update */[/* record */[
                              /* todos : :: */[
                                action[0],
                                state[/* todos */0]
                              ],
                              /* newTodo */state[/* newTodo */1],
                              /* editing */state[/* editing */2],
                              /* nowShowing */state[/* nowShowing */3]
                            ]];
                  }
                })
            ]);
}

exports.createElement = createElement;
/* No side effect */
